################################################################################
# Docker Compose Drupal 8 CI stack.
#
# This is an helper stack to run tests locally on *unix systems.
#
# Project page:
#   https://gitlab.com/mogtofu33/drupal8ci
# Usage:
#   http://dev-drupal.com/en/node/36
################################################################################
version: '3'
services:
  drupal:
    # Drupal included from official docker image + ci tools. Edit in .env file.
    # see https://gitlab.com/mog33/drupal8ci
    image: mogtofu33/drupal8ci:${DRUPAL_VERSION}-${CI_IMAGE_VARIANT}
    # image: registry.gitlab.com/mog33/drupal8ci/drupal8ci:${DRUPAL_VERSION}-${CI_IMAGE_VARIANT}
    ports:
      - "88:80"
      - "4444:4444"
      - "9515:9515"
      - "9222:9222"
    links:
      - mariadb
    volumes:
      # Mount current module, theme or project, mimic Gitlab-ci.
      - ../:/builds
      - ../:/var/www/html
      # Reports folder for results.
      - ../reports:/var/www/reports
      # [OPTIONAL] composer cache folder to speed up the process.
      - ${HOME}/.composer/cache:/var/www/.composer/cache
    working_dir: /builds
    container_name: ci-drupal
    env_file:
      - .env
      - .local.env
  mariadb:
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      # Add my.cnf for better performance.
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
    container_name: ci-mariadb
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
