variables:
  USER_NAME: "ubuntu"
  DRUPAL_FOLDER: "/var/www/htdocs/MY_DRUPAL_ROOT"
  THEME: "MY_THEME_NAME"
  TESTING_HOST: "MY_HOST_OR_IP"
  STAGING_HOST: "MY_HOST_OR_IP"
  PRODUCTION_HOST: "MY_HOST_OR_IP"
  WEB_ROOT: "web"
  PHPQA_IGNORE_DIRS: "--ignoredDirs vendor,bootstrap"
  PHPQA_IGNORE_FILES: "--ignoredFiles Readme.md,style.css,print.css"
  JS_CODE: "${WEB_ROOT}/modules/custom/**/*.js ${WEB_ROOT}/themes/custom/**/*.js"
  JS_CODE_IGNORE: "**/bootstrap/**/*"
  SASS_CODE: "${WEB_ROOT}/themes/custom/**/*.scss,${WEB_ROOT}/themes/custom/**/*.sass"
  TOOLS: "--tools phpcs:5,phpmd:5,phpcpd:0,security-checker:0,parallel-lint:0"
  PHPQA: "v1.19.0"
  REPORT_DIR: "reports"
  DRUPAL_CODER: "2.12"
  PHPQA_REPORT: "--report --buildDir ${REPORT_DIR}"
  PHPQA_CUTSOM_CODE: "--analyzedDirs ${WEB_ROOT}/modules/custom,${WEB_ROOT}/themes/custom ${PHPQA_IGNORE_DIRS} ${PHPQA_IGNORE_FILES}"
  PHPQA_ALL_CODE: "--analyzedDirs ${WEB_ROOT} ${PHPQA_IGNORE_DIRS} ${PHPQA_IGNORE_FILES}"
stages:
  - build
  - test
  - code quality
  - code lint
  - php code metrics
  - deploy to testing
  - deploy to staging
  - deploy to production
image: alpine:latest
.report_template: &report_template
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - ${REPORT_DIR}/*
    expire_in: 1 week
    when: always
.phpqa_template: &phpqa_template
  image: zdenekdrahos/phpqa:${PHPQA}
  before_script:
    - if [ ! -d ./coder/coder_sniffer ]; then curl https://ftp.drupal.org/files/projects/coder-8.x-${DRUPAL_CODER}.tar.gz -o coder.tar.gz -s; fi
    - if [ -f coder.tar.gz ]; then tar xzf coder.tar.gz; fi
    - mkdir -p ${REPORT_DIR}
  after_script:
    - if [ -d ./${REPORT_DIR} ]; then rm -f ./${REPORT_DIR}/*.xml; fi
  <<: *report_template
.node_template: &node_template
  image: node:8-alpine
  <<: *report_template
.ruby_template: &ruby_template
  image: ruby:2-alpine
  <<: *report_template
.ssh_agent_template:
  before_script: &ssh_agent_template
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "${STAGING_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
.build_template: &build_template
  image: composer:latest
  before_script: *ssh_agent_template
  script:
    - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction --ignore-platform-reqs --no-scripts --quiet
    - cp -r drupal/* .
    - composer require drupal/bootstrap --ignore-platform-reqs --no-scripts --quiet
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
      - ./bin
      - ./config
      - ./drush
      - ./scripts
      - ./vendor
      - ./web
      - .env.example
      - .gitignore
      - LICENSE
      - composer.json
      - composer.lock
      - load.environment.php
    expire_in: 1 day
.drupal8ci_template: &drupal8ci_template
  except:
    - master
  image: juampynr/drupal8ci:latest
  services:
    - mariadb:10.3
  before_script:
    - mkdir -p /var/www/html
    - ln -s $CI_PROJECT_DIR/web /var/www/html/web
    - apache2-foreground&
  variables:
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
    DB_URL: "mysql://root@mariadb/drupal8"
    SIMPLETEST_DB: "mysql://root@mariadb/drupal8"
    SIMPLETEST_BASE_URL: "http://localhost"
    BROWSERTEST_OUTPUT_DIRECTORY: "$CI_PROJECT_DIR/web/sites/simpletest"
.drupal8ci_test_template: &drupal8ci_test_template
  <<: *drupal8ci_template
  stage: test
  dependencies:
    - drupal8ci:build
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - coder
    - vendor
build:
  <<: *build_template
  stage: build
  only:
    - master
  cache:
    key: drupal-build-cache
    paths:
      - web
drupal8ci:build:
  <<: *drupal8ci_template
  stage: build
  script:
    - composer install
    - robo install:dependencies
  services:
    - mariadb:10.3
    - selenium/standalone-chrome-debug:3.7.1-beryllium
  artifacts:
    paths:
      - vendor
      - web
  except:
    - master
drupal8ci:unit_kernel_tests:
  <<: *drupal8ci_test_template
  script:
    - robo setup:drupal || true
    - cp .gitlab-ci/phpunit.xml web/core/
    - mkdir -p artifacts/phpunit
    - chmod -R 777 artifacts
    - cd web
    - sudo -E -u www-data
        ../vendor/bin/phpunit -c core
        --debug --verbose --log-junit
        ../artifacts/phpunit/phpunit.xml
        core/modules/node
  artifacts:
    paths:
      - artifacts/phpunit
  when: manual
drupal8ci:code_coverage:
  <<: *drupal8ci_test_template
  script:
    - robo setup:drupal || true
    - cp .gitlab-ci/phpunit.xml web/core/
    - mkdir -p artifacts/coverage-xml
    - mkdir -p artifacts/coverage-html
    - chmod -R 777 artifacts
    - cd web
    - timeout 60m sudo -E -u www-data
        ../vendor/bin/phpunit
        --verbose --debug
        -c core
        --coverage-xml ../artifacts/coverage-xml
        --coverage-html ../artifacts/coverage-html
        --testsuite nonfunctional
        core/modules/node
  artifacts:
    paths:
      - artifacts
  when: manual
code_quality:
  image: docker:stable
  stage: code quality
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD/web"
        --volume "$PWD/web":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
  when: manual
codequality:
  stage: code quality
  <<: *phpqa_template
  script:
    - phpqa ${PHPQA_REPORT} ${TOOLS} ${PHPQA_CUTSOM_CODE}
  only:
    - branches
best practices:
  stage: code quality
  <<: *phpqa_template
  script:
    - phpqa ${PHPQA_REPORT} --config ./phpqa_config/phpcs_drupal_best_practices --tools phpcs:10 ${PHPQA_CUTSOM_CODE}
  only:
    - branches
  allow_failure: true
es lint:
  stage: code lint
  <<: *node_template
  script:
    - apk --no-cache add curl
    - curl https://cgit.drupalcode.org/drupal/plain/.eslintrc.json?h=8.5.x -o ${WEB_ROOT}/.eslintrc.json -s
    - mkdir -p ${WEB_ROOT}/core
    - curl https://cgit.drupalcode.org/drupal/plain/core/.eslintrc.json?h=8.5.x -o ${WEB_ROOT}/core/.eslintrc.json -s
    - curl https://cgit.drupalcode.org/drupal/plain/core/.eslintrc.passing.json?h=8.5.x -o ${WEB_ROOT}/core/.eslintrc.passing.json -s
    - npm install -g eslint eslint-config-airbnb eslint-plugin-import@^2.7.0 eslint-plugin-jsx-a11y@^6.0.2 eslint-plugin-react@^7.4.0
    - eslint --config ./${WEB_ROOT}/core/.eslintrc.passing.json --format html --output-file ${REPORT_DIR}/es-lint-report.html --ignore-pattern ${JS_CODE_IGNORE} ${JS_CODE}
  allow_failure: true
sass lint:
  stage: code lint
  <<: *node_template
  script:
    - npm install -g sass-lint
    - sass-lint ${SASS_CODE} --verbose --format html --output ${REPORT_DIR}/sass-lint-report.html --ignore ${JS_CODE_IGNORE}
  allow_failure: true
markdown lint:
  stage: code lint
  <<: *ruby_template
  script:
    - gem install mdl
    - mdl ./ > ${REPORT_DIR}/markdown_lint.txt
  allow_failure: true
  when: manual
phpmetrics:
  stage: php code metrics
  <<: *phpqa_template
  script:
    - phpqa ${PHPQA_REPORT} --config ./phpqa_config/phpmetrics --tools phpmetrics ${PHPQA_CUTSOM_CODE}
  when: manual
phploc:
  stage: php code metrics
  <<: *phpqa_template
  script:
    - phpqa ${PHPQA_REPORT} --tools phploc ${PHPQA_CUTSOM_CODE}
  when: manual
phpmetrics Drupal:
  stage: php code metrics
  <<: *phpqa_template
  script:
    - phpqa ${PHPQA_REPORT} --config ./phpqa_config/phpmetrics --tools phpmetrics ${PHPQA_ALL_CODE}
  cache:
    key: drupal-build-cache
  when: manual
phploc Drupal:
  stage: php code metrics
  <<: *phpqa_template
  script:
    - phpqa ${PHPQA_REPORT} --tools phploc ${PHPQA_ALL_CODE}
  cache:
    key: drupal-build-cache
  when: manual
deploy to testing:
  stage: deploy to testing
  environment:
    name: testing
    url: http://${TESTING_HOST}
  before_script: *ssh_agent_template
  script:
    - echo "Deploy to testing"
  only:
    - testing
    - master
deploy to staging:
  stage: deploy to staging
  environment:
    name: staging
    url: http://${STAGING_HOST}
  before_script: *ssh_agent_template
  script:
    - echo "Deploy to staging"
  only:
    - staging
    - master
  when: manual
deploy to production:
  stage: deploy to production
  environment:
    name: production
    url: http://${PRODUCTION_HOST}
  before_script: *ssh_agent_template
  script:
    - echo "Deploy to production"
  only:
    - production
    - master
  when: manual
