image: python:alpine

before_script:
  - apk --no-cache add curl python3-dev build-base gcc
  - python -m pip install --upgrade pip
  - pip install mkdocs
  - pip install mkdocs-material

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - 4.x-dev
