# Default common config for Phpqa.
# For more options see:
#   https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml
phpcs:
    standard: Drupal
    ignoreWarnings: true
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        file:
            # checkstyle is always included and overriden
            checkstyle: checkstyle.xml

phpmd:
    standard: .phpmd.xml

pdepend:
    # coverageReport: build/coverage-clover.xml

phpcpd:
    minLines: 5
    minTokens: 70

phpstan:
    allowedErrorsCount: null
    level: 7
    # https://github.com/phpstan/phpstan#configuration
    standard: phpstan.neon

psalm:
    config: psalm.xml
    deadCode: false
    threads: 1
    showInfo: true

# Php file extensions to parse.
extensions:
    - php
    - inc
    - module
    - install
    - test
    - profile
    - theme
