################################################################################
# Docker Compose Drupal 8 CI stack.
#
# This is an helper stack to run Nightwatch.js tests locally on *unix systems.
#
# Project page:
#   https://gitlab.com/mogtofu33/drupal8ci
# Usage:
#   http://dev-drupal.com/en/node/36
################################################################################
version: '3'
services:
  drupal:
    # Choose if you have a Drupal core side of this file.
    # image: mogtofu33/drupal8ci:8.6-selenium-no-drupal
    image: mogtofu33/drupal8ci:8.6-selenium
    ports:
      - "88:80"
    links:
      - mariadb
    volumes:
      # Choose your Drupal folder or custom / theme code folder.
      # - ./drupal:/var/www/html/
      - ./web/modules/custom:/var/www/html/modules/custom
      - ./web/themes/custom:/var/www/html/themes/custom
      # Reports folder for results.
      - ./reports:/var/www/reports
      - ./test/run-tests-ci-locally.sh:/scripts/run-tests-ci-locally.sh
    working_dir: /var/www/html/core
    container_name: ci-drupal
  chromedriver:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
    links:
      - drupal
    container_name: ci-chromedriver
  mariadb:
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      # Add my.cnf for better performance.
      - ./.gitlab-ci/mysql:/etc/mysql:ro
    container_name: ci-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  # Is ~15% faster than MySQL for site install.
  # Must be set in .gitlab-ci/.env.ci if used.
  # pgsql:
  #   image: postgres:alpine
  #   expose:
  #     - "5432"
  #   volumes:
  #     # Add pg_pass to ease drush access.
  #     - ./.gitlab-ci/pgsql/.pg_pass:/home/postgres/.pg_pass
  #   container_name: ci-pgsql
  #   environment:
  #     - POSTGRES_USER=drupal
  #     - POSTGRES_PASSWORD=drupal
  #     - POSTGRES_DB=drupal