################################################################################
# Docker Compose Drupal 8 CI stack.
#
# This is an helper stack to run tests locally on *unix systems.
#
# Project page:
#   https://gitlab.com/mogtofu33/drupal8ci
# Usage:
#   https://developpeur-drupal.com/en/article/drupal-8-javascript-tests-nightwatchjs-and-docker-without-pain
################################################################################
version: '3'
services:
  drupal:
    image: mogtofu33/drupal8ci:8.6
    ports:
      - "88:80"
    links:
      - mariadb
    volumes:
      # Relative custom code folder.
      - ./drupal:/var/www/html/
      # Nightwatch.js report folder for results.
      - ./nightwatch:/var/www/reports/nightwatch
    working_dir: /var/www/html/core
    container_name: ci-drupal
  chromedriver:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
    links:
      - drupal
    container_name: ci-chromedriver
  mariadb:
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      - ./.config/mysql:/etc/mysql:ro
    container_name: ci-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  # Is ~15% faster than MySQL for site install.
  # pgsql:
  #   image: postgres:alpine
  #   expose:
  #     - "5432"
  #   volumes:
  #     # Add pg_pass to ease drush access.
  #     - ./.config/pgsql/.pg_pass:/home/postgres/.pg_pass
  #   container_name: ci-pgsql
  #   environment:
  #     - POSTGRES_USER=drupal
  #     - POSTGRES_PASSWORD=drupal
  #     - POSTGRES_DB=drupal