################################################################################
# Gitlab CI integration for Drupal 9 project or module: tests, code quality,
# linting, metrics and deploy samples.
#
# Project: https://gitlab.com/mog33/gitlab-ci-drupal
# Documentation: https://mog33.gitlab.io/gitlab-ci-drupal
# Issues: https://gitlab.com/mog33/gitlab-ci-drupal/-/issues
# Author: Jean Valverde contact@dev-drupal.com
# License: GPL-3
#
# If you want to support this project, you can
# - Buy me a coffee: https://bit.ly/34jPKcE
# - Hire me as a freelance for any Drupal related work
# - Promote me to any company looking for any Drupal related work
# - Help me with testing / documentation / grammar fixes / use cases...
#
################################################################################

# The ref is relative to the version of the project to use.
include:
  # If hosted on gitlab.com.
  - project: 'mog33/gitlab-ci-drupal'
    ref: 4.x-dev
    file: '/.gitlab-ci/.gitlab-ci-template.yml'
  # If hosted on an other Gitlab instance.
  # - remote: 'https://gitlab.com/mog33/gitlab-ci-drupal/-/raw/4.x-dev/.gitlab-ci/.gitlab-ci-template.yml'

# If needed by your Gitlab-ci instance, you can set global tags for all jobs.
# default:
#   tags:
#     - docker

################################################################################
# Gitlab-CI variables documentation:
# https://docs.gitlab.com/ee/ci/variables/
#
# Variables, can be set here or on
#   Gitlab CI UI > settings > CI/CD > variables
# UI take precedence on variables here.
# https://docs.gitlab.com/ee/ci/variables/README.html#priority-of-environment-variables
################################################################################

variables:
  # This is mandatory to get default variables.
  # For list of variables see
  # https://gitlab.com/mog33/gitlab-ci-drupal/-/raw/4.x-dev/.gitlab-ci/ci/variables.yml
  extends: .default_variables

  # Docker image used for ci, should be the same as include above.
  CI_REF: "4.x-dev"

  # Minor Drupal version to work with, limited to tags on
  # https://hub.docker.com/r/mogtofu33/drupal8ci/tags
  CI_DRUPAL_VERSION:
    value: "9.3"
    description: The version of Drupal to use for this Pipeline.

  # Relative path to the Drupal web root.
  # For a project based on Drupal this is 'web'. Can be 'docroot' or 'html' on
  # some distributions.
  CI_DRUPAL_WEB_ROOT: web

  # Phpunit tests to run, default provide only custom code or if this variable
  # is empty all tests (including Drupal core).
  # https://mog33.gitlab.io/gitlab-ci-drupal/advanced-usage/#phpunit-tests
  CI_PHPUNIT_TESTS: "custom"

  # Specify a group of tests to run rather than all tests in the suite.
  # PHPUNIT_GROUP: my_group_1,my_group_2

  ##############################################################################
  # Override default variables for a module.
  #
  ## Default CI setup is for a 'project' (full Drupal with a composer.json),
  ## next section contains common variables to change for a module (module,
  ## theme or profile). Simply uncomment and adapt dirs to set the CI for a
  ## module.
  #
  # CI_TYPE: module
  ## Code quality dirs, must include your PHP code to check.
  ## Phpstan need autoloading, that's why we use web_root.
  # CI_DIRS_QA: "${CI_WEB_ROOT}/modules/custom"
  ## Eslint / Stylelint files to test.
  # CI_DIRS_JS: "${CI_PROJECT_DIR}/js/*.js"
  # CI_DIRS_YAML: "${CI_PROJECT_DIR}/*.yml"
  # CI_DIRS_CSS: "${CI_PROJECT_DIR}/css/*.css"
  ## Twig files to test.
  # CI_DIRS_TWIG: "${CI_PROJECT_DIR}/templates"
  ## phpmetrics / phpstats dirs to include.
  # CI_DIRS_PHP: "${CI_PROJECT_DIR}"
  ## Set CI_SKIP_XXX variable to 1 to skip.
  ## Security is for a Drupal project with third party.
  # CI_SKIP_SECURITY: 1
  ## If you don't have any css files, you can skip with
  # CI_SKIP_LINT_CSS: 1
  ## If you don't have any javascript files, you can skip with
  # CI_SKIP_LINT_JS: 1
  ## If you don't want to check yaml files, you can skip with
  # CI_SKIP_LINT_YAML: 1
  ## If you don't have any twig files, you can skip with
  # CI_SKIP_LINT_TWIG: 1
  #
  ##############################################################################

  ##############################################################################
  # As a sample here is a list of some variables, see documentation for more
  # variables.
  #
  ## List of CI_DIRS_* variables to define dirs to analyze for specific jobs.
  ## Code quality dirs, must include your PHP code to check.
  #
  # CI_DIRS_QA: "${CI_WEB_ROOT}/modules/custom,${CI_WEB_ROOT}/themes/custom"
  #
  ## Eslint / Stylelint files to test.
  ## Space separated for multiple folders.
  ## Default is to check files under all custom folders.
  #
  # CI_DIRS_JS: "${CI_WEB_ROOT}/**/custom/**/*.js"
  # CI_DIRS_YAML: "${CI_WEB_ROOT}/**/custom/**/*.yml"
  # CI_DIRS_CSS: "${CI_WEB_ROOT}/**/custom/**/css/*.css"
  #
  ## Twig files to test, recursive.
  #
  # CI_DIRS_TWIG: "${CI_WEB_ROOT}/themes/custom"
  #
  ## Phpmetrics / Phpstats dirs to include.
  ## Default is to check all dirs.
  #
  # CI_DIRS_PHP: "${CI_WEB_ROOT}/modules/custom,${CI_WEB_ROOT}/themes/custom"
  #
  ## List of CI_SKIP_* variables, uncomment to skip a job.
  #
  # CI_SKIP_BUILD: 1 # if not running any tests or deploy.
  #
  # CI_SKIP_SECURITY: 1
  #
  # CI_SKIP_TESTS: 1 # Skip all tests, ignore CI_SKIP_TEST_*.
  # CI_SKIP_TEST_UNITKERNEL: 1
  # CI_SKIP_TEST_FUNCTIONAL: 1
  # CI_SKIP_TEST_FUNCTIONALJS: 1
  #
  ## Tests disabled by default because need a specific setup / configuration.
  #
  ## Only needed if you have Behat tests, comment or set to 0 to enable.
  ## https://mog33.gitlab.io/gitlab-ci-drupal/advanced-usage/#behat-tests
  CI_SKIP_TEST_BEHAT: 1
  ## Can use a profile setup or a sql dump file.
  # CI_BEHAT_INSTALL_PROFILE: "minimal"
  # CI_BEHAT_INSTALL_PROFILE: "dump"
  # CI_BEHAT_INSTALL_DUMP: "path/relative/to/project/root/dump.sql.zip"
  #
  ## Only if you have Nightwatch tests in your code.
  ## https://mog33.gitlab.io/gitlab-ci-drupal/advanced-usage/#nightwatchjs
  CI_SKIP_TEST_NIGHTWATCH: 1
  ## Default is '--skiptags core', add your tag.
  # CI_NIGHTWATCH_TESTS: --tag my_module
  #
  # CI_SKIP_QA: 1 # Skip all qa, ignore CI_SKIP_QA_*.
  # CI_SKIP_QA_PHPCS: 1
  # CI_SKIP_QA_PHPMD: 1
  # CI_SKIP_QA_PHPSTAN: 1
  # CI_SKIP_QA_PARALINT: 1
  #
  # CI_SKIP_LINT: 1 # Skip all lint, ignore CI_SKIP_LINT_*.
  # CI_SKIP_LINT_CSS: 1
  # CI_SKIP_LINT_JS: 1
  # CI_SKIP_LINT_YAML: 1
  # CI_SKIP_LINT_TWIG: 1
  #
  # CI_SKIP_METRICS: 1
  #
  ## QA and Metrics tools.
  ## See Phpqa available tools: https://github.com/EdgedesignCZ/phpqa#available-tools
  #
  # CI_TOOLS_METRICS: "phpmetrics,phploc,pdepend"

################################################################################
# Advanced usage with this file, see doc.
# https://mog33.gitlab.io/gitlab-ci-drupal/advanced-usage
################################################################################
