.common_variables: &common_variables
  # Phpunit tests to run, only custom code or empty for all 
  # (included Drupal) see .gitlab-ci/phpunit.xml for settings.
  PHPUNIT_TESTS: "custom"

  # All reports will be available in artifacts from this folder.
  # Do not need any editing as it's for CI only.
  REPORT_DIR: "reports"

  ##############################################################################
  # [TESTING] Next part can be removed for testing only.
  #
  # See Phpqa available tools:
  #   https://github.com/EdgedesignCZ/phpqa#available-tools
  # Allow some errors, this will stop the pipeline if a limit is reached.
  # TOOLS: "--tools phpcs:0,phpmd,phpcpd,parallel-lint"
  TOOLS: "--tools phpcs:0,phpmd"
  # Coding best practices limit, ~10 could be reasonable, to adapt for your
  # project. Current is strict and do not allow errors.
  BEST_PRACTICES: "phpcs:0"

  # Comma separated for phpqa and phpmetrics.
  # Will fail if a folder is empty.
  PHP_CODE: "${WEB_ROOT}/modules/custom"
  # PHP_CODE: "${WEB_ROOT}/themes/custom"
  # PHP_CODE: "${WEB_ROOT}/modules/custom,${WEB_ROOT}/themes/custom"

  ##############################################################################
  # Eslint / Phpqa settings.
  #
  # Space separated for eslint and sass lint.
  JS_CODE: "${WEB_ROOT}/**/custom/**/*.js"
  CSS_FILES: "${WEB_ROOT}/(themes|modules)/custom/**/css/*.css"
  SCSS_FILES: "${WEB_ROOT}/(themes|modules)/custom/**/scss/*.scss"
  SASS_CONFIG: "${CI_PROJECT_DIR}/.gitlab-ci/.sass-lint.yml"

  # PhpQA specific variables to prepare run.
  # Ignore files and dir for all Phpqa tools.
  PHPQA_IGNORE_DIRS: "--ignoredDirs vendor,bootstrap,tests"
  PHPQA_IGNORE_FILES: "--ignoredFiles Readme.md,style.css,print.css,*Test.php"
  # Options for Phpqa to build a report to download, need artifacts set on the
  # job, see '.report' below.
  PHPQA_REPORT: "--report --buildDir ${REPORT_DIR}"
  PHPQA_PHP_CODE: "--analyzedDirs ${PHP_CODE} ${PHPQA_IGNORE_DIRS} ${PHPQA_IGNORE_FILES}"
  PHPQA_ALL_CODE: "--analyzedDirs ${WEB_ROOT} ${PHPQA_IGNORE_DIRS} ${PHPQA_IGNORE_FILES}"

  ##############################################################################
  # [DEPLOY] Global settings for all env used for deploy.
  # Just an example, adapt with 'Deploy jobs definition' at the end of this
  # file.
  ##############################################################################
  #
  # Remote machine access and information.
  # USER_NAME: "ubuntu"
  # DRUPAL_FOLDER: "/var/www/html/MY_DRUPAL_ROOT"
  # Deploy environments configuration, add or remove depending deploy jobs.
  # Testing config, set host or ip
  TESTING_HOST: "localhost"
  # Staging config, set host or ip
  STAGING_HOST: "localhost"
  # Production config, set host or ip
  PRODUCTION_HOST: "localhost"