# Default common config for Phpqa.
# For more options see:
#   https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml
phpcs:
    standard: Drupal
    ignoreWarnings: true
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        file:
            # checkstyle is always included and overridden
            checkstyle: checkstyle.xml
            junit: phpcs-unit.xml

phpmd:
    standard: .phpmd.xml

pdepend:
    coverageReport: /builds/report-unit-kernel/coverage.xml

phpcpd:
    minLines: 5
    minTokens: 70

phpmetrics:
    # junit: build/log-junit.xml

phpstan:
    level: 7
    # https://github.com/phpstan/phpstan#configuration
    standard: phpstan.neon

# Php file extensions to parse.
phpqa:
    ignoredDirs: "vendor,bootstrap,tests,.gitlab-ci"
    ignoredFiles: "Readme.md,style.css,print.css,*Test.php,RoboFile.php"
    report: true
    verbose: false
    execution: parallel
    extensions:
        - php
        - inc
        - module
        - install
        - test
        - profile
        - theme
