# Default common config for Phpqa.
# For more options see:
#   https://github.com/EdgedesignCZ/phpqa/blob/master/.phpqa.yml
phpcs:
    standard: Drupal
    ignoreWarnings: true
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        file:
            # checkstyle is always included and overridden
            checkstyle: checkstyle.xml
            junit: phpcs-unit.xml

phpmd:
    standard: .phpmd.xml

pdepend:
    coverageReport: /builds/report-unit-kernel/coverage.xml

phpcpd:
    minLines: 5
    minTokens: 70

phpmetrics:
    # composer: ../../../../var/www/html/
    junit: /builds/report-unit-kernel/junit-unit-kernel.xml
    # junit: /builds/report-functional/junit-functional.xml
    # junit: /builds/report-functional-javascript/junit-functional-javascript.xml

phpstan:
    # https://phpstan.org/user-guide/rule-levels
    level: 7
    # https://phpstan.org/config-reference
    # https://github.com/mglaman/phpstan-drupal#usage
    standard: phpstan.neon

# Php file extensions to parse.
phpqa:
    ignoredDirs: "vendor,bootstrap,tests,.gitlab-ci"
    ignoredFiles: "Readme.md,style.css,print.css,*Test.php,RoboFile.php"
    report: true
    verbose: false
    execution: parallel
    extensions:
        - php
        - inc
        - module
        - install
        - test
        - profile
        - theme
