<?php

/**
 * @file
 * Dummy module for test.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 *
 * Base implements for a drupal module.
 *
 * @phpstan-ignore-next-line
 */
function my_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_module module.
    case 'help.page.my_module_help':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Help testing Gitlab CI for Drupal 8.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @phpstan-ignore-next-line
 */
function my_module_form_simple_testing_form_alter(&$form, FormStateInterface $form_state) {
  $form['text']['#description'] = t('Please do not fail.');
}
