################################################################################
# Build template used for Build job.
################################################################################

.build_template:
  stage: build
  extends: .variables_test
  before_script:
    - curl -fsSL ${CI_REMOTE_FILES}/RoboFile.php -o RoboFile.php
    - robo ci:prepare
  # When using included Drupal for a module, the cache and artifacts can be
  # removed as we don't install the Drupal with composer.
  #
  # On build we cache the composer and web folders to speed up the tests.
  cache:
    key: "drupal-${CI_COMMIT_REF_NAME}"
    paths:
      - vendor
      - web
  artifacts:
    expire_in: 1 week
    paths:
      # Build files for next steps and deploy/release.
      - vendor
      - web
      - composer.json
      - composer.lock
      # Files from this project.
      - RoboFile.php
      - .gitlab-ci
      # Deprecated Drupal composer project template.
      - drush
      - scripts
      - load.environment.php