################################################################################
# Testing template for phpunit, this provide Apache / Php.
################################################################################

.test_template:
  extends: 
    - .variables_test
    - .artifacts_reports
  dependencies:
    - build
  services:
    - mariadb:latest
  before_script:
    # Start Apache.
    - apache2-foreground&
    - robo ci:prepare
    # Set permissions for tests.
    - mkdir -p ${BROWSERTEST_OUTPUT_DIRECTORY}
    - chown -R www-data:www-data ${BROWSERTEST_OUTPUT_DIRECTORY} && chmod -R 777 ${BROWSERTEST_OUTPUT_DIRECTORY}
