################################################################################
# Testing template for phpunit, this provide Apache / Php.
################################################################################

.test_template:
  extends: 
    - .variables_test
    - .artifacts_reports
  dependencies:
    - build
  services:
    - mariadb:latest
  before_script:
    # Start Apache.
    - apache2-foreground&
    - robo ci:prepare
    - if [ ! -z ${COMPOSER_REPO_PACKAGIST_URL} ]; then
        composer config --global repo.packagist composer ${COMPOSER_REPO_PACKAGIST_URL};
      fi
    - if [ ! -z "${COMPOSER_GITHUB_OAUTH_TOKEN}" ]; then
        composer config -g github-oauth.github.com  ${COMPOSER_GITHUB_OAUTH_TOKEN};
      fi
    # Set permissions for tests.
    - mkdir -p ${BROWSERTEST_OUTPUT_DIRECTORY}
    - chown -R www-data:www-data ${BROWSERTEST_OUTPUT_DIRECTORY} && chmod -R 777 ${BROWSERTEST_OUTPUT_DIRECTORY}
