################################################################################
# Common definition for all qa jobs.
################################################################################

.qa_template:
  extends: .artifacts_reports
  dependencies: build
  before_script:
    - !reference [.scripts, set-registries]
    - !reference [.scripts, ci-prepare]
