################################################################################
# Common definition for all qa jobs.
################################################################################

.qa_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    - robo ci:prepare
    - if [ ! -z ${COMPOSER_REPO_PACKAGIST_URL} ]; then
        composer config --global repo.packagist composer ${COMPOSER_REPO_PACKAGIST_URL};
      fi
    - if [ ! -z "${COMPOSER_GITHUB_OAUTH_TOKEN}" ]; then
        composer config -g github-oauth.github.com  ${COMPOSER_GITHUB_OAUTH_TOKEN};
      fi
    # Avoid phpstan failing.
    - cd /var/www/html
