################################################################################
# Common definition for all qa jobs.
################################################################################

.qa_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    # Coder is needed for Drupal coding standards 'Drupal' and 'DrupalPractice'.
    # Phpstan needed for Code quality.
    - composer require --working-dir='/var/www/.composer' --no-ansi -n drupal/coder:^8.3 dealerdirect/phpcodesniffer-composer-installer:^0.6 mglaman/phpstan-drupal
