################################################################################
# Common definition for all qa jobs.
################################################################################

.qa_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:qa_prepare[collapsed=true]\r\e[0K\e[1;34mRobo ci:prepare, set tools registries"
    - if [ ! -z ${COMPOSER_REPO_PACKAGIST_URL} ]; then
        composer config --global repo.packagist composer ${COMPOSER_REPO_PACKAGIST_URL};
      fi
    - if [ ! -z "${COMPOSER_GITHUB_OAUTH_TOKEN}" ]; then
        composer config -g github-oauth.github.com  ${COMPOSER_GITHUB_OAUTH_TOKEN};
      fi
    # Prepare ci (mirror files in Docker image doc root).
    - curl -fsSL ${CI_REMOTE_FILES}/RoboFile.php -o RoboFile.php
    - robo ci:prepare
    - echo -e "\e[0Ksection_end:`date +%s`:qa_prepare\r\e[0K"
