################################################################################
# Common definition for all qa jobs.
################################################################################

.qa_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    - !reference [.scripts, set-registries]
    - !reference [.scripts, ci-prepare]
  # Allow failure to produce report and warning, not a critical job.
  allow_failure: true