################################################################################
# Common definition for all qa jobs.
################################################################################

.qa_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    - if [ ! -z ${COMPOSER_REPO_PACKAGIST_URL} ]; then
        composer config --global repo.packagist composer ${COMPOSER_REPO_PACKAGIST_URL};
      fi
    - if [ ! -z "${COMPOSER_GITHUB_OAUTH_TOKEN}" ]; then
        composer config -g github-oauth.github.com  ${COMPOSER_GITHUB_OAUTH_TOKEN};
      fi
    # Prepare ci (mirror files in Docker image doc root).
    - curl -fsSL ${CI_REMOTE_FILES}/RoboFile.php -o RoboFile.php
    - robo ci:prepare
    # Avoid phpstan failing.
    - cd ${DOC_ROOT}
