################################################################################
# Common definition for all lint jobs.
################################################################################

.lint_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    - !reference [.scripts, ci-prepare]
    - mkdir -p ${CI_PROJECT_DIR}/report-${CI_JOB_NAME} && chmod 777 ${CI_PROJECT_DIR}/report-${CI_JOB_NAME}
  # Allow failure to produce report and warning, not a critical job.
  allow_failure: true
