################################################################################
# Common definition for all lint jobs.
################################################################################

.lint_template:
  extends: .artifacts_reports
  dependencies: build
  before_script:
    - !reference [.scripts, ci-prepare]
  # Allow failure to produce report and warning, not a critical job.
  allow_failure: true
