################################################################################
# Common definition for all lint jobs.
################################################################################

.lint_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:lint_prepare[collapsed=true]\r\e[0K\e[1;34mRobo ci:prepare, add tools"
    # Support Yarn registry mirror.
    - if [ ! -z "${YARN_REGISTRY}" ]; then
        yarn config set registry ${YARN_REGISTRY};
      fi
    # Prepare ci (mirror files in Docker image doc root).
    - curl -fsSL ${CI_REMOTE_FILES}/RoboFile.php -o RoboFile.php
    - robo ci:prepare
    - mkdir -p ${CI_PROJECT_DIR}/report-${CI_JOB_NAME} && chmod 777 ${CI_PROJECT_DIR}/report-${CI_JOB_NAME}
    # Install packages from core/package.json
    - yarn --cwd ${WEB_ROOT}/core install
    - echo -e "\e[0Ksection_end:`date +%s`:lint_prepare\r\e[0K"
  # Allow failure to produce report and warning, not a critical job.
  allow_failure: true
