################################################################################
# Common definition for all metrics jobs.
################################################################################

.metrics_template:
  extends: .artifacts_reports
  dependencies:
    - build
  before_script:
    - robo ci:prepare
