################################################################################
# Common definition for all metrics jobs.
################################################################################

.metrics_template:
  extends: .artifacts_reports
  before_script:
    - curl -fsSL ${CI_REMOTE_FILES}/RoboFile.php -o RoboFile.php
    - robo ci:prepare
