################################################################################
# [WIP] Use Gitlab pages to publish the results on one page.
# 
# docker run --rm -it -v "/home/mog/code/gitlab-ci-drupal:/builds" -w /builds --env-file local/.env alpine:latest sh
################################################################################

.publish_gitlab_pages_template:
  image: alpine:latest
  script:
    - apk --no-cache add jq tree git
    - git clone https://gitlab.com/mog33/reports--gitlab-ci-drupal.git public
    - cp -r ./report-*/ ./public/
    - cd ./public
    - |
      d=$(ls -d report-* | jq -R -s -c 'split("\n")[:-1]');
      v=$(jq -n env);
      echo "var data={\"dirs\": "$d", \"vars\": "$v" }" > js/data.js
  artifacts:
    paths:
    - public