################################################################################
# [WIP] Publish the results on one page.
################################################################################

.simple_dashboard:
  image: node:lts-alpine
  script:
    - apk --no-cache add jq tree git curl
    - git clone https://gitlab.com/mog33/reports--gitlab-ci-drupal.git dashboard
    - mkdir -p dashboard/src/reports/
    - cp -r ./report-*/ ./dashboard/src/reports/
    - cd ./dashboard
    # Prepare data collection.
    - chmod +x ./src/scripts/ci_vars.sh && ./src/scripts/ci_vars.sh > src/data/data.json
    - yarn install
    - yarn build
  after_script:
    - cp -r dashboard/public .
  artifacts:
    when: always
    paths:
      - public
      - dashboard
