################################################################################
# Variables template used on this project, must be used in your .gitlab-ci.yml:
#
# variables:
#   extends: .default_variables
#
# Gitlab-CI variables documentation:
# https://docs.gitlab.com/ee/ci/variables
################################################################################

.default_variables:

  # Should be the same as 'include: ref:' from .gitlab-ci.yml.
  # Based on branch for this project.
  CI_REF: "4.x-dev"

  # Minor Drupal version to work with, limited to tags on
  # https://hub.docker.com/r/mogtofu33/drupal8ci/tags?name=3.x
  CI_DRUPAL_VERSION: "9.3"

  # Select what you are running CI on, options are:
  #   project
  #     A full Drupal project managed with composer.
  #   module
  #     A single Drupal module or theme.
  CI_TYPE: "project"
  # CI_TYPE: "module"

  # Relative path to the Drupal web root.
  # For a project based on Drupal this is 'web'. Can be 'docroot' or 'html' on
  # some distributions.
  DRUPAL_WEB_ROOT: web

  # Path to the Drupal doc and web root.
  # Drupal official image create symlink /opt/drupal/web > /var/www/html
  # In case of a project we remove /opt/drupal and symlink CI_PROJECT_DIR to
  # /opt/drupal
  DOC_ROOT: "/opt/drupal"
  WEB_ROOT: "/opt/drupal/${DRUPAL_WEB_ROOT}"

  # Phpunit tests to run, default provide only custom code or if this variable
  # is empty all tests (including Drupal core).
  # https://mog33.gitlab.io/gitlab-ci-drupal/advanced-usage/#phpunit-tests
  PHPUNIT_TESTS: "custom"

  # Specify a group of tests to run rather than all tests in the suite.
  # PHPUNIT_GROUP: my_group_1,my_group_2

  # Nightwatch.js tests to run.
  # https://www.drupal.org/docs/8/testing/javascript-testing-using-nightwatch
  # Add --verbose for a full log from Nightwatch if it fail.
  # Default is to run everything except core. For a module / theme, add your tag.
  NIGHTWATCH_TESTS: "--skiptags core"
  # NIGHTWATCH_TESTS: "--tag custom"

  # If not using a db dump, select install profile for Behat tests.
  BEHAT_INSTALL_PROFILE: "minimal"

  # See Phpqa available tools:
  # https://github.com/EdgedesignCZ/phpqa#available-tools
  # ':0' is the number of errors allowed, default here is very strict.
  TOOLS_QA: "phpcs:0,phpmd:0,parallel-lint:0,phpstan:0,phpcpd:0"
  TOOLS_METRICS: "phpmetrics,phploc,pdepend"

  # Composer override to use github oauth token.
  # https://getcomposer.org/doc/06-config.md#github-oauth
  # COMPOSER_GITHUB_OAUTH_TOKEN: ""

  # Composer override to use packagist mirror.
  # COMPOSER_REPO_PACKAGIST_URL: "https://repo.packagist.org"

  # Yarn override to use registry mirror.
  # YARN_REGISTRY: "https://registry.yarnpkg.com"

  ##############################################################################
  # List of DIRS_* variables to define dirs to analyse for specific jobs.
  #
  # Code quality dirs, must include your PHP code to check.
  DIRS_QA: "${WEB_ROOT}/modules/custom,${WEB_ROOT}/themes/custom"
  #
  # Eslint / Stylelint files to test.
  #
  # Configuration files, default is Drupal used for core.
  CONFIG_ESLINT: ${WEB_ROOT}/core/.eslintrc.passing.json
  CONFIG_STYLELINT: ${WEB_ROOT}/core/.stylelintrc.json
  #
  # Space separated for multiple folders.
  # Default is to check files under all custom folders.
  DIRS_JS: "${WEB_ROOT}/**/custom/**/*.js"
  DIRS_YAML: "${WEB_ROOT}/**/custom/**/*.yml"
  DIRS_CSS: "${WEB_ROOT}/**/custom/**/css/*.css"
  #
  # Twig templates files to test.
  DIRS_TWIG: "${WEB_ROOT}/themes/custom"
  #
  # phpmetrics / phpstats dirs to include.
  #
  # Comma separated for multiple folders.
  # Default is to check all custom dirs.
  DIRS_PHP: "${WEB_ROOT}/modules/custom,${WEB_ROOT}/themes/custom"

  ##############################################################################
  # List of SKIP_* variables to skip some jobs.
  # Default is 0, uncomment and set 1 to skip.
  #
  # Skip Build, if not running any tests or deploy.
  SKIP_BUILD: 0
  #
  ##############################################################################
  # Skip all tests jobs.
  SKIP_TESTS: 0
  #
  # OR skip single jobs in tests.
  # For tests information see
  # https://www.drupal.org/docs/8/testing/types-of-tests-in-drupal-8.
  #
  # Phpunit unit,kernel with code coverage and optional Codecove.io support
  SKIP_TEST_UNITKERNEL: 0
  # Phpunit functional tests (browser tests)
  SKIP_TEST_FUNCTIONAL: 0
  # Phpunit functional javascript tests (browser with javascript tests)
  SKIP_TEST_FUNCTIONALJS: 0
  # Nightwatch tests (browser with javascript tests), since Drupal 8.6
  # Currently not fully ready for Drupal so skip by default.
  SKIP_TEST_NIGHTWATCH: 0
  #
  # Third party tests.
  # Symfony security check on composer.lock
  SKIP_TEST_SECURITY: 0
  # Behat tests from behat_tests folder. Demo tests, skip by default.
  SKIP_TEST_BEHAT: 0
  # Accessibility test, skip by default.
  SKIP_TEST_PA11Y: 0
  #
  ##############################################################################
  # Skip PHP QA jobs (phpcs, phpstan, phpmd, phpcpd, parallel-lint)
  SKIP_QA: 0
  #
  ##############################################################################
  # Skip all lint jobs.
  SKIP_LINT: 0
  #
  # OR skip single jobs in lint.
  #
  # CSS lint job with stylelint.
  SKIP_LINT_CSS: 0
  # Javascript lint job with eslint.
  SKIP_LINT_JS: 0
  # Yaml lint job with eslint.
  SKIP_LINT_YAML: 0
  # Twig lint job using symfony console.
  SKIP_LINT_TWIG: 0
  #
  ##############################################################################
  # Skip all metrics jobs (phpmetrics, phploc, pdepend)
  SKIP_METRICS: 0
  #
  ##############################################################################

  ##############################################################################
  # Services used by some jobs.
  #
  DB_DRIVER: mysql
  # DB_DRIVER: pgsql
  # DB_DRIVER: sqlite
  #
  # Database service as docker image and tag.
  SERVICE_DATABASE: "mariadb:10"
  # SERVICE_DATABASE: "mysql:8"
  # SERVICE_DATABASE: "postgres:14"
  SERVICE_DATABASE_PORT: 3306
  # SERVICE_DATABASE_PORT: 5432
  #
  SERVICE_CHROMEDRIVER: "drupalci/webdriver-chromedriver:production"
  SERVICE_CHROMEDRIVER_PORT: 9515
  SERVICE_CHROME: "mogtofu33/chrome-headless:${CI_REF}"
  SERVICE_CHROME_PORT: 9222
  #
  ##############################################################################

  ##############################################################################
  # Other variables for CI only that do not need editing in normal usage.
  #
  # Required by service:mysql/mariadb.
  MYSQL_DATABASE: drupal
  MYSQL_USER: drupal
  MYSQL_PASSWORD: drupal
  MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #
  POSTGRES_PASSWORD: drupal
  POSTGRES_DB: drupal
  POSTGRES_USER: drupal
  #
  # Required by Drupal tests with PHPunit.
  # https://git.drupalcode.org/project/drupal/-/blob/HEAD/core/phpunit.xml.dist
  SIMPLETEST_BASE_URL: "http://build"
  SIMPLETEST_DB: "${DB_DRIVER}://drupal:drupal@db/drupal"
  # SIMPLETEST_DB: "${DB_DRIVER}://root@db/drupal"
  # SIMPLETEST_DB: "sqlite://localhost/:memory:"
  #
  BROWSERTEST_OUTPUT_DIRECTORY: "${WEB_ROOT}/sites/simpletest"
  SYMFONY_DEPRECATIONS_HELPER: "disabled"
  #
  # Functional Javascript tests.
  MINK_DRIVER_ARGS_WEBDRIVER: >
    [
      "chrome",
      {
        "browserName":"chrome",
        "chromeOptions":{
          "w3c":false,
          "args":[
            "--whitelisted-ips",
            "--allowed-origins=chrome",
            "--disable-gpu",
            "--headless",
            "--no-sandbox"
          ]
        }
      },
      "http://chrome:9515"
    ]
  #
  # Behat tests.
  #
  # Settings for Behat with DrupalExtension, match the tests on behat_tests
  # included in this project.
  # https://www.drupal.org/project/drupalextension
  BEHAT_PARAMS: >
    {
      "extensions" : {
        "Drupal\\DrupalExtension" : {
          "drupal" : {
            "drupal_root" : "${WEB_ROOT}"
          }
        }
      }
    }
  # Chrome options, used by mogtofu33/chrome-headless startup.
  # https://peter.sh/experiments/chromium-command-line-switches/
  CHROME_OPTS: "--headless --no-sandbox --window-size=1920,1080 --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --disable-crash-reporter --disable-gpu --disable-software-rasterizer"
  #
  # General settings.
  #
  # Enable Docker network bridge to access services.
  # https://docs.gitlab.com/runner/configuration/feature-flags.html#available-feature-flags
  FF_NETWORK_PER_BUILD: 1
  #
  # Config files location for inclusion if not present locally (from ./.gitlab-ci/).
  CI_REMOTE_FILES: "https://gitlab.com/mog33/gitlab-ci-drupal/-/raw/${CI_REF}/.gitlab-ci"
  #
  # Docker image version used for CI.
  # Should be the same as CI_REF, but can be overridden for some use cases.
  CI_IMAGE_REF: ${CI_REF}
  #
  # Internal verbosity for RoboFile.php scripts.
  CI_VERBOSE: 0
  #
  # Make CI very (very!) verbose in case of problem.
  # https://docs.gitlab.com/ee/ci/variables/#debug-logging
  # CI_DEBUG_TRACE: 1