################################################################################
# Global tests variables.
################################################################################

.variables_test:
  variables:
    # Required by service:mysql.
    MYSQL_DATABASE: "drupal"
    MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    # Required by Drupal tests with PHPunit.
    # https://git.drupalcode.org/project/drupal/-/blob/HEAD/core/phpunit.xml.dist
    SIMPLETEST_BASE_URL: "http://localhost"
    SIMPLETEST_DB: "mysql://root@mariadb/drupal"
    BROWSERTEST_OUTPUT_DIRECTORY: "${WEB_ROOT}/sites/simpletest"
    # BROWSERTEST_OUTPUT_DIRECTORY: "${WEB_ROOT}/sites/default/files/simpletest"
    SYMFONY_DEPRECATIONS_HELPER: "disabled"
    MINK_DRIVER_ARGS_WEBDRIVER: >
      [
        "chrome",
        {
          "browserName":"chrome",
          "chromeOptions":{
            "w3c":false,
            "args":[
              "--whitelisted-ips",
              "--disable-gpu",
              "--headless",
              "--no-sandbox"
            ]
          }
        },
        "http://localhost:9515"
      ]
    # Chrome options.
    # https://peter.sh/experiments/chromium-command-line-switches/
    CHROME_OPTS: "--headless --no-sandbox --window-size=1920,1080 --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --disable-crash-reporter --disable-gpu --disable-software-rasterizer"