################################################################################
# Testing template for phpunit, this provide Apache / Php.
################################################################################

.test_template:
  extends: .artifacts_reports
  dependencies:
    - build
  services:
    - name: ${CI_SERVICE_DATABASE}
      alias: db
  before_script:
    # Start Apache first to ensure it's running.
    - apache2-foreground&
    # Common ci scripts.
    - !reference [.scripts, set-registries]
    - !reference [.scripts, ci-prepare]
    # Set permissions for tests.
    - mkdir -p ${BROWSERTEST_OUTPUT_DIRECTORY} ${CI_WEB_ROOT}/sites/default/files/simpletest
    - chown -R www-data:www-data ${BROWSERTEST_OUTPUT_DIRECTORY} ${CI_WEB_ROOT}/sites
    - chmod -R 777 ${BROWSERTEST_OUTPUT_DIRECTORY} ${CI_WEB_ROOT}/sites

.test_template_behat:
  extends: .test_template
  before_script:
    # Start Apache first to ensure it's running.
    - apache2-foreground&
    # Common ci scripts.
    - !reference [.scripts, set-registries]
    - !reference [.scripts, ci-prepare]
    # Set permissions for tests.
    - mkdir -p ${BROWSERTEST_OUTPUT_DIRECTORY} ${CI_WEB_ROOT}/sites/default/files/simpletest
    - chown -R www-data:www-data ${BROWSERTEST_OUTPUT_DIRECTORY} ${CI_WEB_ROOT}/sites
    - chmod -R 777 ${BROWSERTEST_OUTPUT_DIRECTORY} ${CI_WEB_ROOT}/sites
    - if [ ${CI_TYPE} != "project" ]; then
        cd ${CI_DOC_ROOT};
        robo drupal:require-dev $CI_SKIP_TEST_BEHAT;
        cd ${CI_PROJECT_DIR};
      fi
